#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pip install -U pip
pip install https://github.com/political-memory/django-representatives/archive/master.tar.gz#egg=django-representatives
pip install https://github.com/political-memory/django-representatives-votes/archive/master.tar.gz#egg=django-representatives-votes
pip install -Ue ${OPENSHIFT_REPO_DIR}

python ${OPENSHIFT_REPO_DIR}manage.py migrate --noinput

pushd ${OPENSHIFT_REPO_DIR}
mkdir -p wsgi/static
./manage.py collectstatic --noinput
popd
