#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pip install -U pip
pip install -Ue ${OPENSHIFT_REPO_DIR}

mkdir -p ${OPENSHIFT_DATA_DIR}json
cp ${OPENSHIFT_REPO_DIR}data/SCHEMA.md ${OPENSHIFT_DATA_DIR}json

mkdir -p ${OPENSHIFT_REPO_DIR}wsgi/static
